export const countries: Country[] = [
  {
    id: "us",
    label: "American",
    src: require("../assets/images/flags/us.png"),
  },
  { id: "gb", label: "British", src: require("../assets/images/flags/gb.png") },
  {
    id: "ca",
    label: "Canadian",
    src: require("../assets/images/flags/ca.png"),
  },
  { id: "cn", label: "Chinese", src: require("../assets/images/flags/cn.png") },
  {
    id: "hr",
    label: "Croatian",
    src: require("../assets/images/flags/hr.png"),
  },
  { id: "nl", label: "Dutch", src: require("../assets/images/flags/nl.png") },
  {
    id: "eg",
    label: "Egyptian",
    src: require("../assets/images/flags/eg.png"),
  },
  {
    id: "ph",
    label: "Filipino",
    src: require("../assets/images/flags/ph.png"),
  },
  { id: "fr", label: "French", src: require("../assets/images/flags/fr.png") },
  { id: "gr", label: "Greek", src: require("../assets/images/flags/gr.png") },
  { id: "in", label: "Indian", src: require("../assets/images/flags/in.png") },
  { id: "ie", label: "Irish", src: require("../assets/images/flags/ie.png") },
  { id: "it", label: "Italian", src: require("../assets/images/flags/it.png") },
  {
    id: "jm",
    label: "Jamaican",
    src: require("../assets/images/flags/jm.png"),
  },
  {
    id: "jp",
    label: "Japanese",
    src: require("../assets/images/flags/jp.png"),
  },
  { id: "ke", label: "Kenyan", src: require("../assets/images/flags/ke.png") },
  {
    id: "my",
    label: "Malaysian",
    src: require("../assets/images/flags/my.png"),
  },
  { id: "mx", label: "Mexican", src: require("../assets/images/flags/mx.png") },
  {
    id: "ma",
    label: "Moroccan",
    src: require("../assets/images/flags/ma.png"),
  },
  { id: "pl", label: "Polish", src: require("../assets/images/flags/pl.png") },
  {
    id: "pt",
    label: "Portuguese",
    src: require("../assets/images/flags/pt.png"),
  },
  { id: "ru", label: "Russian", src: require("../assets/images/flags/ru.png") },
  { id: "es", label: "Spanish", src: require("../assets/images/flags/es.png") },
  { id: "th", label: "Thai", src: require("../assets/images/flags/th.png") },
  {
    id: "tn",
    label: "Tunisian",
    src: require("../assets/images/flags/tn.png"),
  },
  { id: "tr", label: "Turkish", src: require("../assets/images/flags/tr.png") },
  {
    id: "ua",
    label: "Ukrainian",
    src: require("../assets/images/flags/ua.png"),
  },
  {
    id: "xx",
    label: "Unknown",
    src: require("../assets/images/flags/globe.png"),
  },
  {
    id: "uy",
    label: "Uruguayan",
    src: require("../assets/images/flags/uy.png"),
  },
  {
    id: "vn",
    label: "Vietnamese",
    src: require("../assets/images/flags/vn.png"),
  },
];
